name: Browser Build & Web Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Prepare Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
    - name: Build web/ and In-Browser LMQL Distribution
      run: cd web && bash deploy.sh
    - uses: actions/upload-artifact@master
      with:
        name: lmql-web-payload
        path: web-deploy

  deploy-main:
    name: Deploy Main Playground 
    runs-on: ubuntu-latest
    needs: [build]
    if:
      contains('
        refs/heads/main
      ', github.ref)
    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: lmql-web-payload
        path: web-deploy
    - name: Deploy to web branch
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web-deploy
        branch: web

